sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera3/depth/image_rect_raw
    queue_size: 5
    near_clipping_plane_distance: 1.0
    far_clipping_plane_distance: 2.0
    shadow_threshold: 1.0
    padding_scale: 1.0
    padding_offset: 0.1
    max_update_rate: 10.0
    filtered_cloud_topic: filtered_cloud
    ns: kinect
